In [ ]:
ADVANTAGES OF NUMPY ARRAYS:
ALLOWS SEVERAL MATHEMATICAL OPEARIONS
FASTER OPERATIONS

In [2]:
import numpy as np


LIST VS NUMPY-TIME TAKEN

In [1]:
from time import process_time

In [4]:
python_list=[i for i in range(10000)]
start_time=process_time()
python_list=[i+5 for i in python_list]
end_time=process_time()
print(end_time-start_time)

0.0018375569999999897


In [6]:
np_array = np.array(list(i for i in range(10000)))  # Convert generator to a list before array creation.
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.002288700999999449


NUMPY ARRAYS


In [7]:
list1=[1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [8]:
np_array=np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

In [9]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [11]:
a.shape

(4,)

In [13]:
b=np.array([(1,2,3,4),(5,6,7,8)])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
b.shape

(2, 4)

In [15]:
c=np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


INITIAL PLACE HOLDERS IN NUMPY ARRAYS


In [19]:
x=np.zeros((4,5),dtype=float)
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [21]:
y=np.ones((5,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [25]:
z=np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [26]:
#create identity matrix
a=np.eye(4)
print(a)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
#create a numpy array with random values

In [29]:
b=np.random.random((3,4))
print(b)

[[0.25880457 0.53672874 0.93766657 0.87249696]
 [0.73383866 0.10649993 0.8031874  0.99111403]
 [0.30430915 0.34618308 0.7174912  0.99195543]]


In [31]:
#random integer values array within a specific range
c=np.random.randint(10,100,(3,5))
print(c)

[[22 53 11 51 45]
 [39 71 66 25 48]
 [23 41 62 56 63]]


In [32]:
#array of evenly spaced values
d=np.linspace(10,30,6)
print(d)


[10. 14. 18. 22. 26. 30.]


In [33]:
#array of evenly spaced values
e=np.arange(10,30,5)
print(e)

[10 15 20 25]


In [34]:
#convert a list to a numpy array
list2=[10,20,30,40,50]
np_array=np.asarray(list2)
print(np_array)
type(np_array)



[10 20 30 40 50]


numpy.ndarray

ANALYSING NUMPY ARRAY

In [35]:
c=np.random.randint(10,90,(5,5))
print(c)

[[78 88 47 11 59]
 [70 17 67 67 28]
 [84 23 31 31 43]
 [59 61 84 27 86]
 [44 58 49 55 58]]


In [36]:
#array dimesnions
print(c.shape)


(5, 5)


In [37]:
#number of dimesnions
print(c.ndim)

2


In [38]:
#number of elemnts in an array
print(c.size)

25


In [39]:
#checking data type values in th array
print(c.dtype)

int64


In [ ]:
mathematical operals on an np array

In [40]:
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [41]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(a)
print(b)

[[8 2 7]
 [0 6 2]
 [2 7 6]]
[[18 11 10]
 [13 10 14]
 [16 17 12]]


In [42]:
print(a)

[[8 2 7]
 [0 6 2]
 [2 7 6]]


In [43]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[26 13 17]
 [13 16 16]
 [18 24 18]]
[[-10  -9  -3]
 [-13  -4 -12]
 [-14 -10  -6]]
[[144  22  70]
 [  0  60  28]
 [ 32 119  72]]
[[0.44444444 0.18181818 0.7       ]
 [0.         0.6        0.14285714]
 [0.125      0.41176471 0.5       ]]


In [44]:
a=np.random.randint(0,10,(3,3))
b=np.random.randint(10,20,(3,3))
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[27 18 24]
 [17 19 16]
 [23 25 22]]
[[-11 -12 -12]
 [ -3  -7 -10]
 [-15 -11 -16]]
[[152  45 108]
 [ 70  78  39]
 [ 76 126  57]]
[[0.42105263 0.2        0.33333333]
 [0.7        0.46153846 0.23076923]
 [0.21052632 0.38888889 0.15789474]]


ARRAY MANIPULATION

In [45]:
array=np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[7 2 9]
 [1 2 6]]
(2, 3)


In [46]:
#transpose of matrix
trans=np.transpose(array)
print(trans)
print(trans.shape)

[[7 1]
 [2 2]
 [9 6]]
(3, 2)


In [47]:
trans2=array.T
print(trans2)
print(trans2.shape)

[[7 1]
 [2 2]
 [9 6]]
(3, 2)


In [50]:
#reshaping arrayy
a=np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[0 8 4]
 [8 9 0]]
(2, 3)


In [54]:
b=a.reshape(3,2)
print(b)
print(b.shape)

[[0 8]
 [4 8]
 [9 0]]
(3, 2)
